export interface Employee {
  id: number;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  birthDate: string;
  basicSalary: number;
  status: string;
  group: string;
  description: string;
}
export interface user {
  id: number;
  email: string;
  password: string;
}

export const dummyData: Employee[] = [
  {
    id: 1,
    basicSalary: 1900040,
    username: 'BlackJefferson',
    firstName: 'Kane',
    lastName: 'Case',
    email: 'kanecase@apextri.com',
    birthDate: '2007-10-12',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Qui id deserunt dolor eiusmod sint cillum elit excepteur anim eu dolor qui.',
  },
  {
    id: 2,
    basicSalary: 8770857,
    username: 'PetraLangley',
    firstName: 'Stevens',
    lastName: 'Santos',
    email: 'stevenssantos@apextri.com',
    birthDate: '1992-06-16',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Aliqua commodo esse pariatur aliqua nulla sint magna.',
  },
  {
    id: 3,
    basicSalary: 9585282,
    username: 'JosieDavidson',
    firstName: 'Cooper',
    lastName: 'Heath',
    email: 'cooperheath@apextri.com',
    birthDate: '1973-02-07',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Cupidatat sit aliquip commodo ex.',
  },
  {
    id: 4,
    basicSalary: 4188593,
    username: 'JeanetteRusso',
    firstName: 'Diane',
    lastName: 'Townsend',
    email: 'dianetownsend@apextri.com',
    birthDate: '1999-11-07',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Qui consequat commodo adipisicing aute proident amet voluptate magna proident.',
  },
  {
    id: 5,
    basicSalary: 8526523,
    username: 'WallerKirby',
    firstName: 'Nanette',
    lastName: 'Weiss',
    email: 'nanetteweiss@apextri.com',
    birthDate: '2010-01-13',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Dolore dolore mollit consectetur aliqua eu dolor commodo.',
  },
  {
    id: 6,
    basicSalary: 9899488,
    username: 'LopezHorn',
    firstName: 'Amanda',
    lastName: 'Mckinney',
    email: 'amandamckinney@apextri.com',
    birthDate: '1990-07-18',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Proident veniam sit laborum velit elit ad cillum.',
  },
  {
    id: 7,
    basicSalary: 1930770,
    username: 'PhelpsKirkland',
    firstName: 'Josephine',
    lastName: 'Noel',
    email: 'josephinenoel@apextri.com',
    birthDate: '2003-05-31',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Velit reprehenderit sunt consectetur officia minim dolor adipisicing ad occaecat nostrud.',
  },
  {
    id: 8,
    basicSalary: 4199703,
    username: 'MeyerMcdaniel',
    firstName: 'Norris',
    lastName: 'Lucas',
    email: 'norrislucas@apextri.com',
    birthDate: '2015-12-15',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Nostrud ut reprehenderit nisi in cillum exercitation nulla aute sit anim mollit Lorem nostrud sit.',
  },
  {
    id: 9,
    basicSalary: 7813568,
    username: 'ShawnWalton',
    firstName: 'Webb',
    lastName: 'Melendez',
    email: 'webbmelendez@apextri.com',
    birthDate: '1992-01-29',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Consectetur quis aliqua aliquip magna consectetur aliquip aliquip dolor non.',
  },
  {
    id: 10,
    basicSalary: 1409220,
    username: 'JeannineMorgan',
    firstName: 'Macias',
    lastName: 'Booker',
    email: 'maciasbooker@apextri.com',
    birthDate: '2010-12-11',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Occaecat elit velit veniam et dolore quis mollit laborum occaecat commodo non laboris.',
  },
  {
    id: 11,
    basicSalary: 2134192,
    username: 'ChristianPatel',
    firstName: 'Brandy',
    lastName: 'Howe',
    email: 'brandyhowe@apextri.com',
    birthDate: '2001-07-28',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Nulla voluptate dolore culpa Lorem anim ullamco ullamco nostrud aute id.',
  },
  {
    id: 12,
    basicSalary: 6061412,
    username: 'LoraineJordan',
    firstName: 'Gwendolyn',
    lastName: 'Koch',
    email: 'gwendolynkoch@apextri.com',
    birthDate: '2012-10-18',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Labore proident nulla fugiat consectetur ut anim ipsum minim nostrud aliquip.',
  },
  {
    id: 13,
    basicSalary: 4912496,
    username: 'HeidiLong',
    firstName: 'Valarie',
    lastName: 'Mcmillan',
    email: 'valariemcmillan@apextri.com',
    birthDate: '1997-11-07',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description: 'Nostrud laborum officia amet do.',
  },
  {
    id: 14,
    basicSalary: 1301088,
    username: 'HouseByrd',
    firstName: 'April',
    lastName: 'Meyers',
    email: 'aprilmeyers@apextri.com',
    birthDate: '1984-07-30',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Cillum tempor quis velit duis duis voluptate anim eu exercitation.',
  },
  {
    id: 15,
    basicSalary: 7419602,
    username: 'OneilMerrill',
    firstName: 'Shana',
    lastName: 'Wilson',
    email: 'shanawilson@apextri.com',
    birthDate: '2004-12-14',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description: 'Sit eu non fugiat culpa labore quis qui sint.',
  },
  {
    id: 16,
    basicSalary: 7778375,
    username: 'MavisNolan',
    firstName: 'Maureen',
    lastName: 'Ewing',
    email: 'maureenewing@apextri.com',
    birthDate: '2010-03-30',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Qui veniam occaecat sint deserunt velit consequat exercitation ea.',
  },
  {
    id: 17,
    basicSalary: 2187170,
    username: 'RhondaSellers',
    firstName: 'Ines',
    lastName: 'Floyd',
    email: 'inesfloyd@apextri.com',
    birthDate: '1998-11-29',
    group: 'Sales',
    status: 'Tidak Aktif',
    description:
      'Ut adipisicing Lorem id occaecat cupidatat laborum elit proident do duis deserunt amet.',
  },
  {
    id: 18,
    basicSalary: 8400189,
    username: 'KeyJohnson',
    firstName: 'Young',
    lastName: 'Whitley',
    email: 'youngwhitley@apextri.com',
    birthDate: '2008-01-20',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Sit consectetur duis dolor ullamco enim incididunt elit eu enim eiusmod sint laborum.',
  },
  {
    id: 19,
    basicSalary: 3980394,
    username: 'JanetGay',
    firstName: 'Melody',
    lastName: 'Foreman',
    email: 'melodyforeman@apextri.com',
    birthDate: '1977-08-10',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Qui sunt aliqua non ad velit aute occaecat.',
  },
  {
    id: 20,
    basicSalary: 7195164,
    username: 'SweetHuffman',
    firstName: 'Rodriguez',
    lastName: 'Compton',
    email: 'rodriguezcompton@apextri.com',
    birthDate: '2003-03-23',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Consequat fugiat nostrud voluptate labore sunt ullamco consequat velit esse duis incididunt consectetur.',
  },
  {
    id: 21,
    basicSalary: 4438861,
    username: 'MathewsSosa',
    firstName: 'Beasley',
    lastName: 'Wells',
    email: 'beasleywells@apextri.com',
    birthDate: '1991-11-06',
    group: 'Sales',
    status: 'Tidak Aktif',
    description:
      'Consectetur excepteur elit aliquip esse veniam velit voluptate quis cupidatat cillum minim.',
  },
  {
    id: 22,
    basicSalary: 2750412,
    username: 'EdwardsMurray',
    firstName: 'Winters',
    lastName: 'Shepherd',
    email: 'wintersshepherd@apextri.com',
    birthDate: '1998-10-08',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'In ut occaecat magna aliqua.',
  },
  {
    id: 23,
    basicSalary: 2258097,
    username: 'LloydBoyd',
    firstName: 'Nola',
    lastName: 'Shannon',
    email: 'nolashannon@apextri.com',
    birthDate: '1974-08-28',
    group: 'Sales',
    status: 'Aktif',
    description: 'Incididunt adipisicing officia Lorem ut.',
  },
  {
    id: 24,
    basicSalary: 2404834,
    username: 'BenitaStewart',
    firstName: 'Joan',
    lastName: 'Ashley',
    email: 'joanashley@apextri.com',
    birthDate: '2005-11-24',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Officia aliquip anim occaecat est in cillum minim.',
  },
  {
    id: 25,
    basicSalary: 2860931,
    username: 'TammieBeck',
    firstName: 'Melanie',
    lastName: 'Benson',
    email: 'melaniebenson@apextri.com',
    birthDate: '2005-08-30',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Aliqua pariatur adipisicing magna ut consectetur exercitation exercitation est aute consectetur.',
  },
  {
    id: 26,
    basicSalary: 6985338,
    username: 'LangPetersen',
    firstName: 'Blanchard',
    lastName: 'Richmond',
    email: 'blanchardrichmond@apextri.com',
    birthDate: '2008-12-27',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Exercitation ullamco incididunt proident enim veniam elit duis amet esse dolor laboris adipisicing nulla est.',
  },
  {
    id: 27,
    basicSalary: 1789392,
    username: 'RatliffBurris',
    firstName: 'Hood',
    lastName: 'Orr',
    email: 'hoodorr@apextri.com',
    birthDate: '2019-05-18',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Dolor excepteur ad eu sunt tempor.',
  },
  {
    id: 28,
    basicSalary: 6222511,
    username: 'CarlaBradley',
    firstName: 'Harriet',
    lastName: 'Wallace',
    email: 'harrietwallace@apextri.com',
    birthDate: '1975-05-02',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Pariatur sint pariatur minim veniam.',
  },
  {
    id: 29,
    basicSalary: 1656526,
    username: 'MartaGallegos',
    firstName: 'Bell',
    lastName: 'Patrick',
    email: 'bellpatrick@apextri.com',
    birthDate: '1995-09-06',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Aute est pariatur dolore incididunt anim amet quis do nostrud.',
  },
  {
    id: 30,
    basicSalary: 3167956,
    username: 'DaleMcneil',
    firstName: 'Avila',
    lastName: 'Gonzales',
    email: 'avilagonzales@apextri.com',
    birthDate: '1975-07-12',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Laborum sunt ipsum veniam ut velit voluptate velit.',
  },
  {
    id: 31,
    basicSalary: 7684567,
    username: 'EarleneRiddle',
    firstName: 'Harper',
    lastName: 'Bonner',
    email: 'harperbonner@apextri.com',
    birthDate: '2013-10-23',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Ad est sunt cupidatat cupidatat nulla minim incididunt cillum occaecat esse quis aliquip incididunt.',
  },
  {
    id: 32,
    basicSalary: 4978865,
    username: 'KatiePuckett',
    firstName: 'Violet',
    lastName: 'Miles',
    email: 'violetmiles@apextri.com',
    birthDate: '1997-08-09',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Et velit mollit minim irure mollit tempor pariatur commodo dolore amet proident sit elit.',
  },
  {
    id: 33,
    basicSalary: 2201569,
    username: 'LavonneSexton',
    firstName: 'Wendi',
    lastName: 'Perez',
    email: 'wendiperez@apextri.com',
    birthDate: '1991-01-27',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Adipisicing dolore proident consequat id adipisicing pariatur laborum culpa.',
  },
  {
    id: 34,
    basicSalary: 1629713,
    username: 'RosalesMorris',
    firstName: 'Joyce',
    lastName: 'French',
    email: 'joycefrench@apextri.com',
    birthDate: '2012-11-05',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Est anim laborum voluptate id tempor et quis eu cupidatat minim velit est exercitation.',
  },
  {
    id: 35,
    basicSalary: 7437282,
    username: 'RoxanneBishop',
    firstName: 'Catherine',
    lastName: 'Cline',
    email: 'catherinecline@apextri.com',
    birthDate: '2021-04-03',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Nisi incididunt reprehenderit incididunt est cillum aute ipsum irure.',
  },
  {
    id: 36,
    basicSalary: 6052857,
    username: 'GabrielleHaley',
    firstName: 'Minerva',
    lastName: 'Doyle',
    email: 'minervadoyle@apextri.com',
    birthDate: '1992-06-12',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Consectetur commodo mollit cillum dolor do aute duis laborum.',
  },
  {
    id: 37,
    basicSalary: 8534146,
    username: 'RussellWaters',
    firstName: 'Aurelia',
    lastName: 'Burns',
    email: 'aureliaburns@apextri.com',
    birthDate: '2019-04-14',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Aute consequat aliquip ipsum et aliquip est aliquip laborum quis incididunt reprehenderit.',
  },
  {
    id: 38,
    basicSalary: 4725735,
    username: 'TracyDyer',
    firstName: 'Latasha',
    lastName: 'Carney',
    email: 'latashacarney@apextri.com',
    birthDate: '2011-05-14',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Elit id in laborum nisi quis occaecat sunt anim.',
  },
  {
    id: 39,
    basicSalary: 6412545,
    username: 'SalinasRobinson',
    firstName: 'Kitty',
    lastName: 'Mills',
    email: 'kittymills@apextri.com',
    birthDate: '1994-03-29',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Occaecat reprehenderit eu elit amet irure duis irure nisi veniam quis reprehenderit pariatur.',
  },
  {
    id: 40,
    basicSalary: 4409335,
    username: 'GayHancock',
    firstName: 'Vance',
    lastName: 'Coleman',
    email: 'vancecoleman@apextri.com',
    birthDate: '1987-07-30',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Lorem in incididunt excepteur aliquip enim in dolore labore non voluptate incididunt.',
  },
  {
    id: 41,
    basicSalary: 7773418,
    username: 'SherriHerrera',
    firstName: 'Ada',
    lastName: 'Odonnell',
    email: 'adaodonnell@apextri.com',
    birthDate: '2018-03-23',
    group: 'Sales',
    status: 'Tidak Aktif',
    description:
      'Commodo incididunt tempor nulla anim laboris amet enim pariatur pariatur.',
  },
  {
    id: 42,
    basicSalary: 6226228,
    username: 'MelissaHammond',
    firstName: 'Kara',
    lastName: 'Cox',
    email: 'karacox@apextri.com',
    birthDate: '1976-11-21',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Esse nulla nisi esse culpa non commodo fugiat nisi non Lorem Lorem.',
  },
  {
    id: 43,
    basicSalary: 2012976,
    username: 'KiddMccarty',
    firstName: 'Marisa',
    lastName: 'Tate',
    email: 'marisatate@apextri.com',
    birthDate: '1990-01-13',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Consectetur anim magna anim ad.',
  },
  {
    id: 44,
    basicSalary: 4056405,
    username: 'JanineRamos',
    firstName: 'Natalie',
    lastName: 'Cote',
    email: 'nataliecote@apextri.com',
    birthDate: '1985-01-21',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Reprehenderit amet labore consectetur dolore aliqua sunt sit labore dolor do.',
  },
  {
    id: 45,
    basicSalary: 7142093,
    username: 'LeeGaines',
    firstName: 'Elnora',
    lastName: 'Newton',
    email: 'elnoranewton@apextri.com',
    birthDate: '1986-08-02',
    group: 'Sales',
    status: 'Aktif',
    description: 'Id sint consectetur magna occaecat consectetur amet commodo.',
  },
  {
    id: 46,
    basicSalary: 2372489,
    username: 'AraceliRaymond',
    firstName: 'Lindsey',
    lastName: 'Alvarado',
    email: 'lindseyalvarado@apextri.com',
    birthDate: '1978-01-14',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Culpa est ut occaecat anim magna laborum mollit reprehenderit aliquip deserunt occaecat sunt.',
  },
  {
    id: 47,
    basicSalary: 3618295,
    username: 'LambertOlsen',
    firstName: 'Sofia',
    lastName: 'Vinson',
    email: 'sofiavinson@apextri.com',
    birthDate: '2005-12-13',
    group: 'Sales',
    status: 'Tidak Aktif',
    description:
      'Aliquip culpa sit consequat commodo velit ullamco nostrud incididunt esse sit eu excepteur eu cillum.',
  },
  {
    id: 48,
    basicSalary: 6747450,
    username: 'SteinHyde',
    firstName: 'Reynolds',
    lastName: 'Kidd',
    email: 'reynoldskidd@apextri.com',
    birthDate: '1995-08-11',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Reprehenderit quis eiusmod aliqua occaecat nisi eu irure nulla exercitation.',
  },
  {
    id: 49,
    basicSalary: 3799034,
    username: 'BentleyPena',
    firstName: 'Joanne',
    lastName: 'Schwartz',
    email: 'joanneschwartz@apextri.com',
    birthDate: '2001-04-02',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Dolore ex ipsum quis nostrud anim nulla duis ut fugiat culpa dolor labore voluptate.',
  },
  {
    id: 50,
    basicSalary: 8748205,
    username: 'HodgeLamb',
    firstName: 'Burns',
    lastName: 'Dale',
    email: 'burnsdale@apextri.com',
    birthDate: '1999-02-16',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description: 'Lorem occaecat dolor occaecat labore laborum dolor non.',
  },
  {
    id: 51,
    basicSalary: 4162407,
    username: 'MargretGibbs',
    firstName: 'Bates',
    lastName: 'Stephens',
    email: 'batesstephens@apextri.com',
    birthDate: '1982-02-22',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Pariatur cillum ullamco velit dolore do sunt.',
  },
  {
    id: 52,
    basicSalary: 6387391,
    username: 'BooneMendez',
    firstName: 'Joni',
    lastName: 'Graham',
    email: 'jonigraham@apextri.com',
    birthDate: '1982-03-17',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Do labore duis duis velit fugiat deserunt dolore aliquip fugiat ad ad.',
  },
  {
    id: 53,
    basicSalary: 3423322,
    username: 'LakeishaRobbins',
    firstName: 'Karyn',
    lastName: 'Battle',
    email: 'karynbattle@apextri.com',
    birthDate: '1973-12-10',
    group: 'Sales',
    status: 'Aktif',
    description: 'Quis consectetur eiusmod anim nisi voluptate velit ut culpa.',
  },
  {
    id: 54,
    basicSalary: 7565337,
    username: 'DanaClark',
    firstName: 'Christina',
    lastName: 'Sears',
    email: 'christinasears@apextri.com',
    birthDate: '2009-06-15',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description: 'Fugiat dolore nulla esse sunt ad.',
  },
  {
    id: 55,
    basicSalary: 1257658,
    username: 'TerrieGarrett',
    firstName: 'Lucinda',
    lastName: 'Hickman',
    email: 'lucindahickman@apextri.com',
    birthDate: '2012-07-08',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Labore Lorem laboris labore anim ad dolor mollit amet eiusmod consectetur.',
  },
  {
    id: 56,
    basicSalary: 6290617,
    username: 'HopperMcleod',
    firstName: 'Tammy',
    lastName: 'Madden',
    email: 'tammymadden@apextri.com',
    birthDate: '2010-09-03',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Nulla deserunt in fugiat ea mollit proident.',
  },
  {
    id: 57,
    basicSalary: 2645529,
    username: 'EliseDominguez',
    firstName: 'Sharlene',
    lastName: 'Marquez',
    email: 'sharlenemarquez@apextri.com',
    birthDate: '1993-09-14',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Ex cupidatat elit eu cillum labore non id.',
  },
  {
    id: 58,
    basicSalary: 4710352,
    username: 'SimoneLester',
    firstName: 'Isabelle',
    lastName: 'Andrews',
    email: 'isabelleandrews@apextri.com',
    birthDate: '1983-06-07',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Dolore occaecat eu dolor quis.',
  },
  {
    id: 59,
    basicSalary: 2154495,
    username: 'RobertaHaynes',
    firstName: 'Justice',
    lastName: 'Ford',
    email: 'justiceford@apextri.com',
    birthDate: '1983-12-05',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Cupidatat ipsum velit proident reprehenderit ullamco do Lorem ut et laborum incididunt.',
  },
  {
    id: 60,
    basicSalary: 6380515,
    username: 'AbbottNunez',
    firstName: 'Lynch',
    lastName: 'Pickett',
    email: 'lynchpickett@apextri.com',
    birthDate: '2005-06-29',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'In consequat cillum labore nisi proident culpa mollit anim eiusmod.',
  },
  {
    id: 61,
    basicSalary: 3200772,
    username: 'JulietFarmer',
    firstName: 'Sara',
    lastName: 'Cunningham',
    email: 'saracunningham@apextri.com',
    birthDate: '2016-11-23',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Enim irure ipsum ullamco excepteur non velit id cupidatat veniam.',
  },
  {
    id: 62,
    basicSalary: 6250963,
    username: 'CruzBrady',
    firstName: 'Kirkland',
    lastName: 'Edwards',
    email: 'kirklandedwards@apextri.com',
    birthDate: '1975-04-26',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description: 'Mollit Lorem cillum fugiat magna.',
  },
  {
    id: 63,
    basicSalary: 2675980,
    username: 'MarianneBenjamin',
    firstName: 'Katrina',
    lastName: 'Park',
    email: 'katrinapark@apextri.com',
    birthDate: '1999-04-21',
    group: 'Sales',
    status: 'Aktif',
    description: 'Nulla velit laborum mollit adipisicing ad elit cupidatat.',
  },
  {
    id: 64,
    basicSalary: 8682917,
    username: 'JosefaSlater',
    firstName: 'Dyer',
    lastName: 'Dillard',
    email: 'dyerdillard@apextri.com',
    birthDate: '2017-01-21',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Cillum exercitation eu anim laboris deserunt excepteur laborum non ipsum laborum culpa.',
  },
  {
    id: 65,
    basicSalary: 5908984,
    username: 'MaldonadoRojas',
    firstName: 'Banks',
    lastName: 'Moran',
    email: 'banksmoran@apextri.com',
    birthDate: '2017-03-27',
    group: 'Sales',
    status: 'Aktif',
    description: 'Proident do reprehenderit irure minim fugiat ut occaecat.',
  },
  {
    id: 66,
    basicSalary: 9169111,
    username: 'LorettaHolder',
    firstName: 'Kelley',
    lastName: 'Dorsey',
    email: 'kelleydorsey@apextri.com',
    birthDate: '2019-02-21',
    group: 'Sales',
    status: 'Tidak Aktif',
    description:
      'Nisi dolor id occaecat consectetur duis sunt mollit commodo reprehenderit enim dolore velit.',
  },
  {
    id: 67,
    basicSalary: 4781229,
    username: 'SantosGould',
    firstName: 'Ellison',
    lastName: 'Mann',
    email: 'ellisonmann@apextri.com',
    birthDate: '2021-12-10',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Consequat velit labore excepteur officia sint exercitation elit qui anim dolore quis commodo laboris.',
  },
  {
    id: 68,
    basicSalary: 9870797,
    username: 'SusanMullins',
    firstName: 'Nellie',
    lastName: 'Mayer',
    email: 'nelliemayer@apextri.com',
    birthDate: '1998-02-07',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Et ut pariatur minim magna est.',
  },
  {
    id: 69,
    basicSalary: 7000683,
    username: 'SilviaConley',
    firstName: 'Martin',
    lastName: 'Washington',
    email: 'martinwashington@apextri.com',
    birthDate: '1978-02-08',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Ea aliqua irure cillum ipsum sint pariatur enim sunt.',
  },
  {
    id: 70,
    basicSalary: 6077685,
    username: 'TrishaLewis',
    firstName: 'Della',
    lastName: 'Wilkerson',
    email: 'dellawilkerson@apextri.com',
    birthDate: '1990-02-09',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Fugiat laborum irure qui qui nulla do eu dolor sint ullamco aliqua duis do.',
  },
  {
    id: 71,
    basicSalary: 1057277,
    username: 'AltheaSmith',
    firstName: 'Vang',
    lastName: 'House',
    email: 'vanghouse@apextri.com',
    birthDate: '2006-06-27',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Quis exercitation aute esse ad Lorem proident eiusmod officia.',
  },
  {
    id: 72,
    basicSalary: 8317413,
    username: 'LupeHicks',
    firstName: 'Duke',
    lastName: 'Vaughn',
    email: 'dukevaughn@apextri.com',
    birthDate: '2005-04-24',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description: 'Adipisicing mollit Lorem pariatur excepteur nostrud.',
  },
  {
    id: 73,
    basicSalary: 4649324,
    username: 'HoganLynch',
    firstName: 'Vonda',
    lastName: 'Keith',
    email: 'vondakeith@apextri.com',
    birthDate: '2021-03-07',
    group: 'IT Divisi',
    status: 'Aktif',
    description:
      'Sit quis elit ut nisi reprehenderit cupidatat commodo ea elit.',
  },
  {
    id: 74,
    basicSalary: 1826325,
    username: 'JanisFoster',
    firstName: 'Bianca',
    lastName: 'Maldonado',
    email: 'biancamaldonado@apextri.com',
    birthDate: '2004-08-28',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Nostrud incididunt magna non laboris voluptate eu esse.',
  },
  {
    id: 75,
    basicSalary: 9789439,
    username: 'ClaytonEverett',
    firstName: 'Iva',
    lastName: 'Montgomery',
    email: 'ivamontgomery@apextri.com',
    birthDate: '1982-01-07',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Quis eu est cillum ad esse non.',
  },
  {
    id: 76,
    basicSalary: 8066652,
    username: 'VaughanBecker',
    firstName: 'Foreman',
    lastName: 'Cantrell',
    email: 'foremancantrell@apextri.com',
    birthDate: '2011-11-21',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Eu veniam nostrud fugiat in incididunt.',
  },
  {
    id: 77,
    basicSalary: 7034654,
    username: 'WalkerBriggs',
    firstName: 'Velma',
    lastName: 'Bird',
    email: 'velmabird@apextri.com',
    birthDate: '1984-07-01',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Reprehenderit aliquip nisi laborum enim do eu dolore.',
  },
  {
    id: 78,
    basicSalary: 1180385,
    username: 'OliverOrtega',
    firstName: 'Lilly',
    lastName: 'Ratliff',
    email: 'lillyratliff@apextri.com',
    birthDate: '2020-08-09',
    group: 'IT Divisi',
    status: 'Aktif',
    description: 'Excepteur deserunt mollit aute voluptate labore ut qui.',
  },
  {
    id: 79,
    basicSalary: 3431812,
    username: 'JessieCohen',
    firstName: 'Anastasia',
    lastName: 'Baker',
    email: 'anastasiabaker@apextri.com',
    birthDate: '2007-02-16',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description: 'Eu elit adipisicing Lorem nisi.',
  },
  {
    id: 80,
    basicSalary: 1032932,
    username: 'ReginaStevenson',
    firstName: 'Patty',
    lastName: 'Richard',
    email: 'pattyrichard@apextri.com',
    birthDate: '1991-12-26',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Velit fugiat non ut duis.',
  },
  {
    id: 81,
    basicSalary: 9810505,
    username: 'VanessaHowell',
    firstName: 'French',
    lastName: 'Chaney',
    email: 'frenchchaney@apextri.com',
    birthDate: '1998-09-19',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description:
      'Qui occaecat mollit sint minim occaecat eiusmod adipisicing sint sunt anim est exercitation anim quis.',
  },
  {
    id: 82,
    basicSalary: 2028652,
    username: 'RoseHudson',
    firstName: 'Kris',
    lastName: 'Martin',
    email: 'krismartin@apextri.com',
    birthDate: '1988-11-01',
    group: 'Sales',
    status: 'Aktif',
    description: 'Magna commodo eiusmod eiusmod ut.',
  },
  {
    id: 83,
    basicSalary: 9896846,
    username: 'WeissHumphrey',
    firstName: 'Lynnette',
    lastName: 'Chase',
    email: 'lynnettechase@apextri.com',
    birthDate: '1973-06-23',
    group: 'Sales',
    status: 'Tidak Aktif',
    description:
      'Commodo duis elit ipsum ullamco ullamco irure duis non minim dolore.',
  },
  {
    id: 84,
    basicSalary: 5586900,
    username: 'JudySheppard',
    firstName: 'Marcy',
    lastName: 'Beasley',
    email: 'marcybeasley@apextri.com',
    birthDate: '1973-02-28',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Laborum Lorem in enim irure sunt irure aliquip in excepteur culpa pariatur ad.',
  },
  {
    id: 85,
    basicSalary: 9321654,
    username: 'RaeMalone',
    firstName: 'Madden',
    lastName: 'Chapman',
    email: 'maddenchapman@apextri.com',
    birthDate: '2003-09-23',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Occaecat elit Lorem reprehenderit magna in adipisicing officia cillum exercitation ut pariatur aute.',
  },
  {
    id: 86,
    basicSalary: 9826927,
    username: 'MaryanneSoto',
    firstName: 'Skinner',
    lastName: 'Macdonald',
    email: 'skinnermacdonald@apextri.com',
    birthDate: '1997-12-08',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Fugiat consequat ex eu nostrud.',
  },
  {
    id: 87,
    basicSalary: 1929478,
    username: 'McculloughWatson',
    firstName: 'Melendez',
    lastName: 'Leonard',
    email: 'melendezleonard@apextri.com',
    birthDate: '2013-01-27',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description:
      'Exercitation elit consectetur id exercitation consequat excepteur anim pariatur occaecat.',
  },
  {
    id: 88,
    basicSalary: 3821635,
    username: 'SuarezHayden',
    firstName: 'Sullivan',
    lastName: 'Price',
    email: 'sullivanprice@apextri.com',
    birthDate: '1976-03-21',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Laborum sint laborum ex ut est excepteur laborum incididunt magna id proident ea.',
  },
  {
    id: 89,
    basicSalary: 7548090,
    username: 'HollyConrad',
    firstName: 'Jarvis',
    lastName: 'Morse',
    email: 'jarvismorse@apextri.com',
    birthDate: '1989-05-24',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Commodo eu incididunt duis magna veniam eiusmod ex adipisicing irure.',
  },
  {
    id: 90,
    basicSalary: 1812317,
    username: 'RandolphCarlson',
    firstName: 'Michele',
    lastName: 'Dean',
    email: 'micheledean@apextri.com',
    birthDate: '2009-03-10',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Deserunt aliqua nostrud in adipisicing anim eu ullamco anim in ullamco.',
  },
  {
    id: 91,
    basicSalary: 6659306,
    username: 'BaldwinCombs',
    firstName: 'Dickson',
    lastName: 'Rivera',
    email: 'dicksonrivera@apextri.com',
    birthDate: '1997-06-04',
    group: 'Sales',
    status: 'Aktif',
    description: 'Incididunt amet nostrud enim sint nisi labore officia id.',
  },
  {
    id: 92,
    basicSalary: 1635403,
    username: 'JeanneGoodwin',
    firstName: 'Edwina',
    lastName: 'Villarreal',
    email: 'edwinavillarreal@apextri.com',
    birthDate: '2021-05-17',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description: 'Sunt sint sit dolor proident.',
  },
  {
    id: 93,
    basicSalary: 5744810,
    username: 'WalshGalloway',
    firstName: 'Shepherd',
    lastName: 'Benton',
    email: 'shepherdbenton@apextri.com',
    birthDate: '2000-11-28',
    group: 'Marketing',
    status: 'Tidak Aktif',
    description: 'Commodo nisi ullamco duis do dolor anim.',
  },
  {
    id: 94,
    basicSalary: 5008254,
    username: 'TerrellMcintyre',
    firstName: 'Osborne',
    lastName: 'Grant',
    email: 'osbornegrant@apextri.com',
    birthDate: '1992-08-26',
    group: 'Sales',
    status: 'Tidak Aktif',
    description: 'Enim velit nisi sint est exercitation duis veniam.',
  },
  {
    id: 95,
    basicSalary: 8934128,
    username: 'MeadowsHendricks',
    firstName: 'Alfreda',
    lastName: 'Coffey',
    email: 'alfredacoffey@apextri.com',
    birthDate: '2017-03-02',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Mollit sint cupidatat ea nostrud veniam ex nisi tempor et excepteur pariatur.',
  },
  {
    id: 96,
    basicSalary: 6353597,
    username: 'LinaGamble',
    firstName: 'Magdalena',
    lastName: 'Mcclure',
    email: 'magdalenamcclure@apextri.com',
    birthDate: '1993-03-30',
    group: 'IT Divisi',
    status: 'Tidak Aktif',
    description: 'Labore enim proident esse ad elit commodo.',
  },
  {
    id: 97,
    basicSalary: 1454392,
    username: 'MargoPreston',
    firstName: 'Clara',
    lastName: 'Leblanc',
    email: 'claraleblanc@apextri.com',
    birthDate: '1978-10-27',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Magna incididunt aliquip labore ullamco voluptate.',
  },
  {
    id: 98,
    basicSalary: 5863191,
    username: 'CamilleHall',
    firstName: 'Huber',
    lastName: 'Cleveland',
    email: 'hubercleveland@apextri.com',
    birthDate: '1997-04-27',
    group: 'Marketing',
    status: 'Aktif',
    description:
      'Exercitation amet duis quis exercitation eu Lorem nostrud sint in exercitation minim proident.',
  },
  {
    id: 99,
    basicSalary: 8260798,
    username: 'MarleneFuentes',
    firstName: 'Kline',
    lastName: 'Black',
    email: 'klineblack@apextri.com',
    birthDate: '1981-06-05',
    group: 'Marketing',
    status: 'Aktif',
    description: 'Sunt est ullamco incididunt sint officia est.',
  },
  {
    id: 100,
    basicSalary: 8821691,
    username: 'PalmerConner',
    firstName: 'Valerie',
    lastName: 'Perry',
    email: 'valerieperry@apextri.com',
    birthDate: '1985-07-12',
    group: 'Sales',
    status: 'Aktif',
    description:
      'Laborum velit ad amet qui anim cillum velit aute incididunt duis ipsum laborum dolor eu.',
  },
];

export const dummyUsers: user[] = [
  { id: 1, email: 'test@mail.com', password: 'admin123' },
];

export const Group = [
  'Marketing',
  'Sales',
  'Accounting',
  'Finance',
  'Executive Officers',
  'Security',
  'Senior Frontend',
  'Senior Backend',
  'Junior Frontend',
  'Junior Backend',
];

export const addUserData = (value: any) => {
  value.id = dummyUsers.length + 1;
  dummyUsers.push(value);
};

export const inputData = (value: any) => {
  value.id = dummyData.length + 1;
  dummyData.push(value);
};

export const deleteData = (id: number) => {
  const indexData = dummyData.findIndex((data) => data.id == id);
  dummyData.splice(indexData, 1);

  return dummyData;
};

const re =
  /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;

export const isEmail = (email: string) => {
  return email.match(re);
};

export const checkDate = (date: Date) => {
  const today = new Date();
  date = new Date(date);

  if (today < date) return true;
  return false;
};

export const currencyChange = (value: string) => {
  return parseFloat(value.replace(/,/g, ''))
    .toFixed(2)
    .toString()
    .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
};
